web:
  image: sandipholambe/csvserver:latest
  container_name: gaurav
  ports:
    - 9393:9393
  volumes:
    - ./inputFile:/csvserver/inputdata
 prometheus:
   image: prom/prometheus:v2.22.0
   ports:
     - 9090:9090
